language: python
python:
  - 3.6
  - 3.7
  - 3.8

services:
  - docker

before_install:
    - docker pull aaraney/nwm-djs:2.0

install:
    - pip3 install -e .

script:
    - |-
        cd pocono_test_case &&
        unzip pocono_test_case &&
        cd pocono_test_case
    - python3 -m djs perturbation-engine pe_setup.yml
    - sed -i 's|cpus.*|cpus:to_space"0-1"|; s|to_space| |' js_setup.yml
    - python3 -m djs job-scheduler js_setup.yml